#!/usr/bin/env bash
#XXX: must use vim insted of nvm aka neovim because the latter doesn't show the \ prefixed lines with brown color anymore (NVIM v0.11.0-dev-16+gb3e045740-dirty) but it used to(in neovim-0.9.5)
/usr/bin/vim todo_rust.wofl
